unique_ids:
  forms:
    Form1: DWKTWA47TPGVIATXEJVBSLRMFBLH3FZH
  modules: {}
  server_modules: {}
  assets:
    standard-page.html: IBKTR3GKHF72L7LUSOTARNE45D7FDVZ2
    theme.css: KW4JI6VPDEZIAKNK3IQHTU42NUGA6RAB
